---
title: "Demystifying Components of Riding Hailing"
author: "Chirag Lakhanpal, Shikha Sharma, Abhishek Pradhan"
# date: "today"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---


```{r init, include=FALSE}
# Installing necessary packages 

library(arrow)
library(ezids)
library(knitr)
library(dplyr)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

## 1 Exordium


## 2 Data Preparation

### 2.1 Gather Data

```{r Reading Data, results='markup'}

# Loading main data for New York yellow taxi trips
raw_data <- data.frame(read_parquet('../RawData/yellow_tripdata_2022-06.parquet'))

# Loading main data for Zone information
zone_lookup <- data.frame(read.csv("../Data/Taxi_Zone_Lookup.csv"))

data_des <- data.frame(read.csv('../Data/Data_Definitions.csv'))

kable(head(raw_data),align = 'l')

```


### 2.2 Data Descriptors

```{r, results='markup'}
kable(head(data_des),align = 'l')
```

```{r, results='markup'}
kable(head(zone_lookup),align = 'l')
```

### 2.3 Data Statistics

```{r Checking Data types, results='markup'}

# More dive into data

str(raw_data)
str(zone_lookup)

kable(sapply(raw_data, typeof))

```

### 2.4 Data Manipulation

```{r Removing excess columns}

head(raw_data)

drop <- c("store_and_fwd_flag", "extra", "mta_tax","improvement_surcharge","congestion_surcharge","airport_fee","total_amount")

raw_data <- raw_data[,!(colnames(raw_data) %in% drop)]
```

```{r Renaming columns}
colnames(raw_data)[2] <- 'pickup_time'
colnames(raw_data)[3] <- 'dropoff_time'
colnames(raw_data)[7] <- 'PULocation'
colnames(raw_data)[8] <- 'DOLocation'
```

```{r Summary for Raw Data, results='markup'}
xkablesummary(raw_data,bso = 'bordered')
```

#### 2.4.1 Looking up values

```{r D}

# Looking up Zone for Zone IDs 

raw_data <- inner_join(raw_data,zone_lookup,by=c('PULocation' = 'LocationID'))

# Dropping irrelevant column added from above join

drop <- c('Zone','service_zone','PULocation')
raw_data <- raw_data[,!(colnames(raw_data) %in% drop)]
colnames(raw_data)[12] <- 'PULocation'

# Performing above exercise for drop off location

raw_data <- inner_join(raw_data,zone_lookup,by=c('DOLocation' = 'LocationID'))
drop <- c('Zone','service_zone','DOLocation')
raw_data <- raw_data[,!(colnames(raw_data) %in% drop)]
colnames(raw_data)[12] <- 'DOLocation'

```

#### 2.4.2 Adding calculated column of interest

```{r tip percentage}

# Adding tip percentage

raw_data['tip_perc'] <- c(round((raw_data['tip_amount']/raw_data['fare_amount'])*100,0))

# Adding trip duration

raw_data['trip_duration'] <- raw_data['dropoff_time'] - raw_data['pickup_time'] / 60

difftime(ymd_hms(raw_data['dropoff_time']) - ymd_hms(raw_data['pickup_time']), units = 'mins')

head(raw_data,n = 10)

```


## 3 Explanatory Data Analysis



## 4 Conclusion






